### ISSUE TITLE
No XPI for release 1.7.0

### ISSUE THREAD

**Issue by ncalexan** [mozilla-extensions/remote-settings-devtools#104]
I see no XPI for the latest release, release 1.7.0, at https://github.com/mozilla-extensions/remote-settings-devtools/releases/tag/1.7.0.

**Comment by leplatrem** [comment]
Thanks for reporting.

There was an issue with the extension linter and we couldn't obtain the signed XPI until recently. I just added it to the release entry.

https://github.com/mozilla-extensions/remote-settings-devtools/releases/download/1.7.0/remote-settings-devtools-1.7.0.xpi
