### ISSUE TITLE
`InvalidSignatureError` for every collection with Environment: Dev

### ISSUE THREAD

**Issue by ncalexan** [mozilla-extensions/remote-settings-devtools#105]
I'm using Firefox Nightly 103, build ID `20220531065724`, addon version 1.6.0, and `Environment: Dev`.  The configuration fails for me:
```
WebExtensions: Error with main/addons-manager-settings InvalidSignatureError: Invalid content signature (main/addons-manager-settings)
    InvalidSignatureError resource://services-settings/RemoteSettingsClient.jsm:120
    _validateCollectionSignature resource://services-settings/RemoteSettingsClient.jsm:856
```
(This is one collection but they're all the same error.)  The underlying NSS/pkix error isn't much help:
```
[Parent 65439: StreamTrans #2]: D/ContentSignatureVerifier CSVerifier: The supplied chain is bad (Result::ERROR_UNKNOWN_ISSUER)
[Parent 65439: StreamTrans #2]: D/ContentSignatureVerifier CSVerifier: Signature verification failed
```
Perhaps a missing intermediate?  Perhaps the dev root hash is no longer correct?  I have tried with Environment: Stage and it succeeds, so this really looks like a dev configuration issue.

**Comment by leplatrem** [comment]
Thanks Nick for your report. I'm sorry for the impact it could have :(

The issue is not related to the DevTools. The collections signatures in our DEV server were not refreshed, and were almost all pointing to expired certificates.

I ran the scheduled job manually, but an AWS Lambda is supposed to do this job. [A fix is pending deploy](https://github.com/mozilla-services/cloudops-deployment/pull/4640) and should fix the issue. /cc @smarnach

**Comment by ncalexan** [comment]
> Thanks Nick for your report. I'm sorry for the impact it could have :(

Almost none!  I rolled over to use stage and local for my testing and now it should be addressed.
 
> The issue is not related to the DevTools. The collections signatures in our DEV server were not refreshed, and were almost all pointing to expired certificates.
> 
> I ran the scheduled job manually, but an AWS Lambda is supposed to do this job. [A fix is pending deploy](https://github.com/mozilla-services/cloudops-deployment/pull/4640) and should fix the issue. /cc @smarnach

This sounds great.  Thanks for figuring out what was happening -- I was stumped.

**Comment by leplatrem** [comment]
The signature are now refreshed regularly, and we now receive alerts if something goes wrong.
