### ISSUE TITLE
Preview mode is not read in by the dropdown menu correctly.

### ISSUE THREAD

**Issue by gregtatum** [mozilla-extensions/remote-settings-devtools#175]
Steps to reproduce:

* Open a new profile.
* Open about:config
* Verify `services.settings.preview_enabled` is empty
* Install and open remote settings devtools
* Change dropdown from Prod to "Prod (preview)"
* Go to about:config
* Verify `services.settings.preview_enabled` is true
* Close Firefox
* Re-open Firefox
* Verify `services.settings.preview_enabled` is true
* Open remote settings devtools

Expected:

"Prod (preview)" is still selected.

Actual:

"Prod" is selected.

**Comment by leplatrem** [comment]
Which version of the browser are you running?

Do you run with the env `MOZ_REMOTE_SETTINGS_DEVTOOLS=1`to be able to switch servers?
