### ISSUE TITLE
Impossible to switch to stage?

### ISSUE THREAD

**Issue by leplatrem** [mozilla-extensions/remote-settings-devtools#44]
Reported by QA 

> We cannot switch Remote Settings to Stage using the Dev Tools add-on because the Environment dropdown menu automatically jumps back to "Prod" when selecting "Stage". This is also reproducible on a clean profile without any pref changes, only on Beta and Dev Edition 73.
I have also attached the following .gif highlighting the issue.

**Comment by leplatrem** [comment]
Possible explanation:
- extension detects environment from server URL given by `RemoteSettings.inspect()` 
- since https://bugzilla.mozilla.org/show_bug.cgi?id=1598562  server URL cannot be changed in beta/release

**Comment by ncloudioj** [comment]
I also ran into this on 73 release on Windows. Is there any way to work around it?

**Comment by leplatrem** [comment]
> I also ran into this on 73 release on Windows. Is there any way to work around it?

You can run Firefox with an env var `XPCSHELL_TEST_PROFILE_DIR=foo` and you'll be able to change the URL. https://searchfox.org/mozilla-central/rev/cc0f9906505d0ffa0d3a29a80142379e21cb5fb2/services/settings/Utils.jsm#44

**Comment by mostlygeek** [comment]
When this happens, let's tell the user with some sort of notification.   It is be confusing for users to fail silently and they have to find this issue and use nightly or with the environment variable above.

**Comment by Mardak** [comment]
> You can run Firefox with an env var `XPCSHELL_TEST_PROFILE_DIR=foo`

Sounds like this workaround might be broken starting with 99 (beta/release):
https://bugzilla.mozilla.org/show_bug.cgi?id=1272255
https://bugzilla.mozilla.org/show_bug.cgi?id=1757741#c4

**Comment by Mardak** [comment]
Running this from the Browser Console before selecting the Environment dropdown seems to work:
```js
XPCOMUtils.defineLazyPreferenceGetter(
  ChromeUtils.import("resource://services-settings/Utils.jsm").Utils,
  "SERVER_URL",
  "services.settings.server"
)
```

**Comment by juliandescottes** [comment]
For information, we are landing a fix to support a new env variable, which will work similarly to the previous workaround with `XPCSHELL_TEST_PROFILE_DIR=foo`. But great to see that you found another workaround, would never have thought about that :) 

See https://bugzilla.mozilla.org/show_bug.cgi?id=1758645, the new environment variable would be `MOZ_REMOTE_SETTINGS_DEVTOOLS=1`.

Patch still needs to reach mozilla-central and then be uplifted to beta.
