### ISSUE TITLE
A "TypeError: client.openCollection is not a function" error is displayed when trying to clear local data

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-extensions/remote-settings-devtools#45]
**[Affected versions]:**
- Firefox Nightly 76.0a1, Build ID 20200318213346

**[Affected Platforms]:**
- Windows 10 x64
- macOS 10.14

**[Prerequisites]:**
- Have a new Firefox profile created.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and [install the Remote Settings Devtools addon](https://github.com/mozilla-extensions/remote-settings-devtools/releases/download/1.2.0/remote-settings-devtools@mozilla.com-1.2.0-signed.xpi).
2. Click the Green Puzzle icon from the browser toolbar.
3. Click the "Clear ALL local data" or any of the "Clear local data" buttons.
4. Observe the behavior.

**[Expected result]:**
- The local data is cleared and the local timestamps are blank.

**[Actual result]:**
- The "TypeError: client.openCollection is not a function" error is displayed and local data is not cleared.

**[Regression window]:**
- 9:07.40 INFO: Last good revision: c5a8b641d9050b73462b24cfea6dd89833e560b6
- 9:07.40 INFO: First bad revision: 9c1e03c2f3504efdd15b76678fce55317f281241
- 9:07.40 INFO: Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=c5a8b641d9050b73462b24cfea6dd89833e560b6&tochange=9c1e03c2f3504efdd15b76678fce55317f281241

- Looks like [bug 1620185](https://bugzilla.mozilla.org/show_bug.cgi?id=1620185) has caused this issue.

**[Notes]:**
- Attached a screen recording of the issue:
![remote-settings-devtools-clearlocaldataerror](https://user-images.githubusercontent.com/18304511/77046225-38c60300-69cb-11ea-84a7-955f15b11b15.gif)

**Comment by leplatrem** [comment]
Thanks for reporting! I opened a pull-request, we'll release a new version once reviewed :)
