### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by leplatrem** [mozilla-extensions/remote-settings-devtools#65]
On top of https://github.com/mozilla-extensions/xpi-manifest/blob/master/docs/releasing-a-xpi.md#kicking-off-the-release

0. If this is your first time releasing, please ask in [#addons-pipeline](https://mozilla.slack.com/archives/CMKP7NPKN) to be added to the correct LDAP group for releasing the `remote-settings-devtools` XPI.
1. Update package, manifest and update info. Tag, push to Github
2. Go to [Ship-it](https://shipit.mozilla-releng.net), login in the top right, create XPI release, select `remote-settings-devtools` as the XPI, select the revision with the commit hash associated with the tag that's being released, click `CREATE RELEASE` --> `SUBMIT`.

![Screenshot from 2021-09-17 13-29-54](https://user-images.githubusercontent.com/546692/133816633-1f637f4a-1c5d-4f2f-9a4a-4fe2e737ea4c.png)

3. Go to list of pending releases, https://shipit.mozilla-releng.net/xpi **SCROLL DOWN TO THE BOTTOM**

4. Click `Build` --> `SCHEDULE`

![Screenshot from 2021-09-17 17-44-22](https://user-images.githubusercontent.com/546692/133816640-bd5c7172-1462-4b75-952f-7a69027089b4.png)

5. Go to [#addons-pipeline](https://mozilla.slack.com/archives/CMKP7NPKN) and request signoff `Hi! There's a new version of the remote-settings-devtools, remote-settings-devtools-X.Y.Z, ready for sign-off. It does THIS AND THAT. Thank you!`

**Comment by matt-boris** [comment]
We should make these steps a part of the `README` and close this "issue"

**Comment by leplatrem** [comment]
Yes! It's a matter of doing it one more time maybe :)

What do you think if you try to do the process and see if these steps are sufficient?

**Comment by matt-boris** [comment]
> What do you think if you try to do the process and see if these steps are sufficient?

Exactly what I was thinking @leplatrem!
