### ISSUE TITLE
Add support for the DEV environment

### ISSUE THREAD

**Issue by leplatrem** [mozilla-extensions/remote-settings-devtools#66]
We now have a proper DEV instance at https://settings.dev.mozaws.net/v1

We could add an entry in the environment drop-down.
The signature config (root hash) is the same as STAGE.

Loading dumps must be disabled with `Services.prefs.setBoolPref("services.settings.load_dump", false);`. Note that this is probably going to change in the future with the implementation of https://bugzilla.mozilla.org/show_bug.cgi?id=1702759

**Comment by matt-boris** [comment]
[1.6.0 Release](https://github.com/mozilla-extensions/remote-settings-devtools/releases/tag/1.6.0) has been created.

Waiting on [Ship-It access](https://bugzilla.mozilla.org/show_bug.cgi?id=1740098) in order to release the new version.
